name: Run test cases


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Initialize Conda
      run: conda init bash

    - name: Create and activate Conda environment
      shell: bash -l {0}
      run: |
        conda create -n myenv python=${{ matrix.python-version }} -y
        echo "CONDA_PREFIX=$(conda env list | grep myenv | awk '{print $2}')" >> $GITHUB_ENV
        conda activate myenv
        conda install pip -y

    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        conda activate myenv
        pip install -r src/roy_on_ray/requirements.txt

    - name: Install additional Python dependencies
      shell: bash -l {0}
      run: |
        conda activate myenv
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda activate myenv
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install the package and test with pytest
      shell: bash -l {0}
      run: |
        conda activate myenv
        make install
        make test
